apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: /
  newName: /
- name: 686710509719.dkr.ecr.ap-northeast-2.amazonaws.com/pda-project
  newName: 686710509719.dkr.ecr.ap-northeast-2.amazonaws.com/pda-project
  newTag: "20231016161113"
resources:
- ../../resources